### ISSUE TITLE
currently not parsable in CSV.read() but parses fine in DataFrame's readable()

### ISSUE THREAD

**Issue by tcovert** [JuliaData/CSV.jl#86]
I have an example file which reads fine in `readtable()` from `DataFrames` but will not read using `CSV.read()': 
https://www.dropbox.com/s/hrutgyidhojujv9/WellIndex_20160811.csv?dl=0

Since I am able to get this data into Julia using DataFrames I am personally in good shape, but I understand that eventually the plan is to deprecate `readtable()` in favor of this package, so it would be cool if it is eventually possible to parse files like this.

Thanks in advance if you are able get `CSV.read()` to read this.

posted [here](https://github.com/JuliaComputing/TextParse.jl/issues/19) last month as well...

**Comment by nalimilan** [comment]
Could you reduce the file to a smaller test case? The Dropbox link made my browser hang for seconds before I could download the file. It would be helpful to remove any rows and columns which are not needed to reproduce the problem.

**Comment by tcovert** [comment]
The error message I get is kind of cryptic, so its hard to know which rows/cols are triggering the error:
```
julia> wi = CSV.read("WellIndex_20160811.csv", DataTable)
ERROR: CSV.CSVError("Unexpected start of quote (34), use \"9234\" to type \"34\"")
Stacktrace:
 [1] readsplitline!(::Array{CSV.RawField,1}, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::UInt8, ::UInt8, ::UInt8, ::Base.AbstractIOBuffer{Array{UInt8,1}}) at /Users/tcovert/.julia/v0.6/CSV/src/io.jl:89
 [2] #Source#12(::String, ::CSV.Options, ::Int64, ::Int64, ::Array{DataType,1}, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:137
 [3] (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}) at ./<missing>:0
 [4] #Source#11(::UInt8, ::UInt8, ::UInt8, ::String, ::Int64, ::Int64, ::Array{DataType,1}, ::Bool, ::Bool, ::DateFormat{Symbol("yyyy-mm-dd"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'}}}, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T, ::String) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:25
 [5] #read#30(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::Type{DataTables.DataTable}) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:301
 [6] read(::String, ::Type{DataTables.DataTable}) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:301

```

**Comment by tcovert** [comment]
Here is the example file with just the subset of columns that I believe are problematic.  I still don't know which rows, but when I remove all three of the right-most columns from this file, the new example and original example both successfully parse:

https://www.dropbox.com/s/o7qrq8nxjhf7uy3/WellIndex_20160811_b.csv?dl=0

this file is 2 megs, the original was 9 or so...

**Comment by tcovert** [comment]
Alright I've got it down to the row that is problematic.  This file should be 2 kb, and I know that the final row is the one with the failure (I've included the 24 non-problematic rows that precede it as well).  This seems to be an escaping problem, but telling CSV.read() what escape character to look for also doesn't solve the problem:
```
CSV.read("WellIndex_20160811_b.csv", DataFrame, escapechar = '"')
ERROR: CSV.CSVError("Unexpected start of quote (34), use \"3434\" to type \"34\"")
Stacktrace:
 [1] readsplitline!(::Array{CSV.RawField,1}, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::UInt8, ::UInt8, ::UInt8, ::Base.AbstractIOBuffer{Array{UInt8,1}}) at /Users/tcovert/.julia/v0.6/CSV/src/io.jl:89
 [2] #Source#12(::String, ::CSV.Options, ::Int64, ::Int64, ::Array{DataType,1}, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:137
 [3] (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}) at ./<missing>:0
 [4] #Source#11(::UInt8, ::UInt8, ::Char, ::String, ::Int64, ::Int64, ::Array{DataType,1}, ::Bool, ::Bool, ::DateFormat{Symbol("yyyy-mm-dd"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'}}}, ::Int64, ::Int64, ::Int64, ::Bool, ::Type{T} where T, ::String) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:25
 [5] (::Core.#kw#Type)(::Array{Any,1}, ::Type{CSV.Source}, ::String) at ./<missing>:0
 [6] #read#30(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::Type{DataFrames.DataFrame}) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:301
 [7] (::CSV.#kw##read)(::Array{Any,1}, ::CSV.#read, ::String, ::Type{DataFrames.DataFrame}) at ./<missing>:0
```

https://www.dropbox.com/s/jp1etj7x6g4zu0i/WellIndex_20160811_c.csv?dl=0

**Comment by cjprybol** [comment]
Thank you for documenting this issue @tcovert. I agree that the problem appears to be with escaping.

The way this file loads in the Dropbox preview and in Excel has the last value in the last column (row 24, column OriginalWellName) represented as `NORTH DAKOTA STATE "A" #1`, which I presume is the desired output from `CSV.read`.

The value of that cell in plain text is `"NORTH DAKOTA STATE ""A"" #1"`, which you'll notice is formatted differently than the rest of the dataset

```
APINo,FileNo,CurrentWellName,LeaseName,OriginalWellName
3.3101E+13,1,BLUM     1,BLUM,PIONEER OIL & GAS #1
3.3001E+13,2,DAVIS WELL     1,DAVIS WELL,DAVIS WELL #1
3.3009E+13,3,GREAT NORTH. O AND G PIPELINE CO.     1,GREAT NORTH. O AND G PIPELINE CO.,GREAT NORTHERN OIL & GAS PIPELINE #1
... skipping rows with the same formatting as 1-3 ...
3.3043E+13,24,NORTH DAKOTA STATE A     1,NORTH DAKOTA STATE A,"NORTH DAKOTA STATE ""A"" #1"
```

The fact that the final value is the only quoted value doesn't seem to be causing any issues, but using the same character `"` for both quoting (`"` is the default) and escaping is creating an issue.

A temporary workaround would be to preprocess the file and replace parenthesis-escaped quotes with backslash-escaped quotes (i.e. `""` -> `\"`).

A quick fix you can use at the REPL is:
```julia
escape_double_quote(s::String) = replace(s, "\"\"", "\\"")
cleaned_file = IOBuffer(escape_double_quote(readstring(open("Downloads/WellIndex_20160811_c.csv"))))
CSV.read(cleaned_file, DataTable)
```

which works
```julia
julia> CSV.read(cleaned_file, DataTable)
24×5 DataTables.DataTable
│ Row │ APINo     │ FileNo │ CurrentWellName                         │ LeaseName                         │ OriginalWellName                     │
├─────┼───────────┼────────┼─────────────────────────────────────────┼───────────────────────────────────┼──────────────────────────────────────┤
│ 1   │ 3.3101e13 │ 1      │ BLUM     1                              │ BLUM                              │ PIONEER OIL & GAS #1                 │
│ 2   │ 3.3001e13 │ 2      │ DAVIS WELL     1                        │ DAVIS WELL                        │ DAVIS WELL #1                        │
│ 3   │ 3.3009e13 │ 3      │ GREAT NORTH. O AND G PIPELINE CO.     1 │ GREAT NORTH. O AND G PIPELINE CO. │ GREAT NORTHERN OIL & GAS PIPELINE #1 │
│ 4   │ 3.3043e13 │ 4      │ ROBINSON PATD LAND     1                │ ROBINSON PATD LAND                │ ROBINSON PAT'D LAND #1               │
│ 5   │ 3.3031e13 │ 5      │ GLENFIELD OIL COMPANY     1             │ GLENFIELD OIL COMPANY             │ GLENFIELD OIL COMPANY #1             │
│ 6   │ 3.3023e13 │ 6      │ NORTHWEST OIL CO.     1                 │ NORTHWEST OIL CO.                 │ #1                                   │
│ 7   │ 3.3055e13 │ 7      │ OIL SYNDICATE     1                     │ OIL SYNDICATE                     │ H. HANSON OIL SYNDICATE #1           │
│ 8   │ 3.3043e13 │ 8      │ ARMSTRONG     1                         │ ARMSTRONG                         │ ARMSTRONG #1                         │
│ 9   │ 3.3075e13 │ 9      │ GEHRINGER     1                         │ GEHRINGER                         │ GEHRINGER #1                         │
│ 10  │ 3.3101e13 │ 10     │ PETROLEUM CO.     1                     │ PETROLEUM CO.                     │ VELVA PETROLEUM CO. #1               │
│ 11  │ 3.3047e13 │ 11     │ BURNSTAD     1                          │ BURNSTAD                          │ BURNSTAD #1                          │
│ 12  │ 3.3105e13 │ 12     │ OIL COMPANY     1                       │ OIL COMPANY                       │ BIG VIKING #1                        │
│ 13  │ 3.3105e13 │ 13     │ NELS KAMP     1                         │ NELS KAMP                         │ NELS KAMP #1                         │
│ 14  │ 3.3059e13 │ 14     │ EXPLORATION-NORTH DAKOTA     1          │ EXPLORATION-NORTH DAKOTA          │ EXPLORATION-NORTH DAKOTA #1          │
│ 15  │ 3.3065e13 │ 15     │ WACHTER     16-18                       │ WACHTER                           │ E. L. SEMLING #1                     │
│ 16  │ 3.3029e13 │ 16     │ FRANKLIN INVESTMENT CO.     1           │ FRANKLIN INVESTMENT CO.           │ FRANKLIN INVESTMENT CO. #1           │
│ 17  │ 3.3077e13 │ 17     │ RUDDY BROS     1                        │ RUDDY BROS                        │ RUDDY BROS #1                        │
│ 18  │ 3.3101e13 │ 18     │ J. H. KLINE     1                       │ J. H. KLINE                       │ J. H. KLINE #1                       │
│ 19  │ 3.3015e13 │ 19     │ STRATIGRAPHIC TEST     1                │ STRATIGRAPHIC TEST                │ STRATIGRAPHIC TEST #1                │
│ 20  │ 3.3071e13 │ 20     │ AANSTAD STRATIGRAPHIC TEST     1        │ AANSTAD STRATIGRAPHIC TEST        │ AANSTAD STRATIGRAPHIC TEST #1        │
│ 21  │ 3.3057e13 │ 21     │ FRITZ LEUTZ     1                       │ FRITZ LEUTZ                       │ FRITZ LEUTZ #1                       │
│ 22  │ 3.3055e13 │ 22     │ VAUGHN HANSON     1                     │ VAUGHN HANSON                     │ VAUGHN HANSON #1                     │
│ 23  │ 3.3029e13 │ 23     │ J. J. WEBER     1                       │ J. J. WEBER                       │ J. J. WEBER #1                       │
│ 24  │ 3.3043e13 │ 24     │ NORTH DAKOTA STATE A     1              │ NORTH DAKOTA STATE A              │ NORTH DAKOTA STATE \"A\" #1          │
```

I think you're supposed to be able to use the `transform` argument of `CSV.read` to apply pre-processing like this on a streaming, column-by-column basis, although when I tried
```julia
CSV.read("Downloads/WellIndex_20160811_c.csv", DataTable, transforms=Dict(24 => s -> escape_double_quote(s)))
```
that didn't work for me, so we might need to work on that too.

I don't have a fix yet, but I think we should handle this particular case of using `"` for both escaping and quoting because Excel handles it that way (as does `readtable`). For all other instances, I think we should throw an error if any two quoting/escaping/delimiting characters are the same. `readsplitline!` currently does a single, left-right pass over each line in the dataset and we may need to change the order of operations on that to first find the delimiters, then the quoted fields, and then handle escape characters within quoted fields, which will be less efficient but should handle this.

**Comment by tcovert** [comment]
Thanks for the thoughtful reply, @cjprybol.  

I couldn't get this line to execute on the terminal:
```
escape_double_quote(s::String) = replace(s, "\"\"", "\\"")
```
(it seemed to be waiting for me to close another string)

but this did work:
```
escape_double_quote(s::String) = replace(s, "\"\"", "\\\"")
```
and when I used it I was able to read the entire file (not just the MWE subset above) in.

**Comment by quinnj** [comment]
Alrighty, this is now fixed on master. This is indeed an interesting case and I'm a little surprised we didn't run into it before. In particular, the problem was trying to parse quoted strings where the `escapechar` and `quotechar` happened to be the same character; in those cases, we had a hard time detecting the end of the quoted string since we viewed the last `quotechar` as an `escapechar` and just kept parsing.

**Comment by tcovert** [comment]
@quinnj, thanks for adding that.  I'm guessing that this fix works under some version of `DataFrames`, but I couldn't make it work under either master or the latest tagged release:

Last tagged release:
```
julia> Pkg.status()
10 required packages:
 - CSV                           0.1.5+             master
 - CSVFiles                      0.3.1
 - DataArrays                    0.6.2
 - DataFrames                    0.10.1
 - DataValueArrays               0.0.1
 - FileIO                        0.5.1
 - IndexedTables                 0.3.2
 - JuliaDB                       0.2.2
 - NullableArrays                0.1.2
 - Query                         0.7.2
31 additional packages:
 - BinDeps                       0.7.0
 - Compat                        0.31.0
 - Dagger                        0.3.1
 - DataStreams                   0.2.0
 - DataStructures                0.7.1
 - DataValues                    0.2.0
 - DocStringExtensions           0.4.0
 - Documenter                    0.11.2
 - GZip                          0.3.0
 - Glob                          1.1.1
 - HTTP                          0.4.3
 - Homebrew                      0.5.9
 - IterableTables                0.5.1
 - JSON                          0.14.0
 - Logging                       0.3.1
 - MacroTools                    0.3.7
 - MbedTLS                       0.5.0
 - NamedTuples                   4.0.0
 - Nulls                         0.0.6
 - PooledArrays                  0.1.1
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - SHA                           0.5.1
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.3.3
 - StatsBase                     0.19.0
 - TableTraits                   0.0.1
 - TableTraitsUtils              0.1.0
 - TextParse                     0.1.9
 - URIParser                     0.2.0
 - WeakRefStrings                0.3.0

julia> using CSV, DataFrames
INFO: Recompiling stale cache file /Users/tcovert/.julia/lib/v0.6/CSV.ji for module CSV.

julia> wi = CSV.read("WellIndex_20160811.csv", escapechar = '"')
ERROR: MethodError: no method matching streamtypes(::Type{DataFrames.DataFrame})
Closest candidates are:
  streamtypes(::Type{CSV.Sink}) at /Users/tcovert/.julia/v0.6/CSV/src/Sink.jl:32
Stacktrace:
 [1] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'H'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'M'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'S'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'s'}}}}, ::Type{DataFrames.DataFrame}) at /Users/tcovert/.julia/v0.6/DataStreams/src/DataStreams.jl:208
 [2] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'H'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'M'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'S'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'s'}}}}, ::Type{DataFrames.DataFrame}) at ./<missing>:0
 [3] #read#27(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:286
 [4] (::CSV.#kw##read)(::Array{Any,1}, ::CSV.#read, ::String, ::Type{T} where T) at ./<missing>:0 (repeats 2 times)
```  

DataFrames master:
```
julia> using CSV, DataFrames
INFO: Recompiling stale cache file /Users/tcovert/.julia/lib/v0.6/CSV.ji for module CSV.

julia> Pkg.status()
10 required packages:
 - CSV                           0.1.5+             master
 - CSVFiles                      0.3.1
 - DataArrays                    0.6.2
 - DataFrames                    0.10.1+            master
 - DataValueArrays               0.0.1
 - FileIO                        0.5.1
 - IndexedTables                 0.3.2
 - JuliaDB                       0.2.2
 - NullableArrays                0.1.2
 - Query                         0.7.2
31 additional packages:
 - BinDeps                       0.7.0
 - CategoricalArrays             0.2.0
 - Compat                        0.31.0
 - Dagger                        0.3.1
 - DataStreams                   0.2.0
 - DataStructures                0.7.1
 - DataValues                    0.2.0
 - DocStringExtensions           0.4.0
 - Documenter                    0.11.2
 - Glob                          1.1.1
 - HTTP                          0.4.3
 - Homebrew                      0.5.9
 - IterableTables                0.5.1
 - JSON                          0.14.0
 - Logging                       0.3.1
 - MacroTools                    0.3.7
 - MbedTLS                       0.5.0
 - NamedTuples                   4.0.0
 - Nulls                         0.0.6
 - PooledArrays                  0.1.1
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - SHA                           0.5.1
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.3.3
 - StatsBase                     0.19.0
 - TableTraits                   0.0.1
 - TableTraitsUtils              0.1.0
 - TextParse                     0.1.9
 - URIParser                     0.2.0
 - WeakRefStrings                0.3.0

julia> wi = CSV.read("WellIndex_20160811.csv", escapechar = '"')
ERROR: MethodError: no method matching zero(::Type{Nulls.Null})
Closest candidates are:
  zero(::Type{Base.LibGit2.GitHash}) at libgit2/oid.jl:106
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:82
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:124
  ...
Stacktrace:
 [1] Type at /Users/tcovert/.julia/v0.6/WeakRefStrings/src/WeakRefStrings.jl:77 [inlined]
 [2] allocate(::Type{Nulls.Null}, ::Int64, ::Array{UInt8,1}) at /Users/tcovert/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:233
 [3] grow_to!(::Array{AbstractArray{T,1} where T,1}, ::Base.Iterators.Rest{Base.Generator{UnitRange{Int64},DataFrames.##167#170{Array{UInt8,1},Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,Union,Union,DataType,DataType,DataType,DataType}}},Int64}, ::Int64) at ./array.jl:498
 [4] grow_to!(::Array{Array{Int64,1},1}, ::Base.Iterators.Rest{Base.Generator{UnitRange{Int64},DataFrames.##167#170{Array{UInt8,1},Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,Union,Union,DataType,DataType,DataType,DataType}}},Int64}, ::Int64) at ./array.jl:506 (repeats 2 times)
 [5] grow_to!(::Array{Any,1}, ::Base.Iterators.Rest{Base.Generator{UnitRange{Int64},DataFrames.##167#170{Array{UInt8,1},Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,Union,Union,DataType,DataType,DataType,DataType}}},Int64}) at ./array.jl:491
 [6] _collect(::UnitRange{Int64}, ::Base.Iterators.Rest{Base.Generator{UnitRange{Int64},DataFrames.##167#170{Array{UInt8,1},Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,DataType,Union,DataType,DataType,DataType,DataType,DataType,Union,Union,DataType,DataType,DataType,DataType}}},Int64}, ::Base.EltypeUnknown, ::Base.SizeUnknown) at ./array.jl:446
 [7] #DataFrame#164(::Array{UInt8,1}, ::Type{T} where T, ::DataStreams.Data.Schema{true,Tuple{Int64,Int64,WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},Union{Nulls.Null, WeakRefString{UInt8}},Int64,WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},Int64,WeakRefString{UInt8},Union{Nulls.Null, WeakRefString{UInt8}},WeakRefString{UInt8},Nulls.Null,Nulls.Null,Nulls.Null,WeakRefString{UInt8},Union{Float64, Nulls.Null},Union{Float64, Nulls.Null},WeakRefString{UInt8},WeakRefString{UInt8},Nulls.Null,WeakRefString{UInt8}}}, ::Type{DataStreams.Data.Field}, ::Bool) at /Users/tcovert/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:276
 [8] (::Core.#kw#Type)(::Array{Any,1}, ::Type{DataFrames.DataFrame}, ::DataStreams.Data.Schema{true,Tuple{Int64,Int64,WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},Union{Nulls.Null, WeakRefString{UInt8}},Int64,WeakRefString{UInt8},WeakRefString{UInt8},WeakRefString{UInt8},Int64,WeakRefString{UInt8},Union{Nulls.Null, WeakRefString{UInt8}},WeakRefString{UInt8},Nulls.Null,Nulls.Null,Nulls.Null,WeakRefString{UInt8},Union{Float64, Nulls.Null},Union{Float64, Nulls.Null},WeakRefString{UInt8},WeakRefString{UInt8},Nulls.Null,WeakRefString{UInt8}}}, ::Type{DataStreams.Data.Field}, ::Bool) at ./<missing>:0
 [9] #stream!#17(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Function, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'H'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'M'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'S'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'s'}}}}, ::Type{DataFrames.DataFrame}) at /Users/tcovert/.julia/v0.6/DataStreams/src/DataStreams.jl:215
 [10] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},DateFormat{Symbol("yyyy-mm-dd\\THH:MM:SS.s"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'H'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'M'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'S'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'s'}}}}, ::Type{DataFrames.DataFrame}) at ./<missing>:0
 [11] #read#27(::Bool, ::Dict{Int64,Function}, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at /Users/tcovert/.julia/v0.6/CSV/src/Source.jl:286
 [12] (::CSV.#kw##read)(::Array{Any,1}, ::CSV.#read, ::String, ::Type{T} where T) at ./<missing>:0 (repeats 2 times)
```

I don't *think* either of these are actually parsing errors, but the error message for the second case is pretty complicated so I could be wrong.

**Comment by nalimilan** [comment]
You need to upgrade DataStreams to version 0.3.0. Things are currently a bit complicated because the current release of DataFrames is incompatible with the more recent DataStreams/CSV/CategoricalArray versions, so the package manager can get confused if you checkout the master branch of some packages manually.

**Comment by fab4ap** [comment]
A similar issue remains. The file I am trying to read works with readtable() and also with R's read.csv() - but fails with CSV.read() - I can upload the file if needed.
Here is the error message:

_ERROR: CSV.ParsingException("error parsing a `Int64` value on column 9, row 114; encountered '.'")
Stacktrace:
 [1] parsefield(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Type{Int64}, ::CSV.Options{Void}, ::Int64, ::Int64, ::Base.RefValue{CSV.ParsingState}, ::CSV.##6#7) at e:\JuliaPkgDir\.julia\v0.6\CSV\src\parsefields.jl:167
 [2] macro expansion at e:\JuliaPkgDir\.julia\v0.6\DataStreams\src\query.jl:484 [inlined]
 [3] stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::DataStreams.Data.Query{0x01,Tuple{DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},1,1,:pltid,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},2,2,:avgstdage,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},3,3,:avght,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},4,4,:diacnt,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},5,5,:sumd,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},6,6,:avgdia,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},7,7,:sumba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},8,8,:avgba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},9,9,:pmort,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},10,10,:alldiasum,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},11,11,:alldiacount,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},12,12,:allbasum,nothing,()}},(),nothing,nothing}, ::Type{DataStreams.Data.Field}, ::DataFrames.DataFrameStream{Tuple{Array{Union{Int64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Int64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Int64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1},Array{Union{Int64, Missings.Missing},1},Array{Union{Float64, Missings.Missing},1}}}, ::DataStreams.Data.Schema{true,Tuple{Union{Int64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Int64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Float64, Missings.Missing},Union{Int64, Missings.Missing},Union{Float64, Missings.Missing},Union{Int64, Missings.Missing},Union{Float64, Missings.Missing}}}, ::Int64) at e:\JuliaPkgDir\.julia\v0.6\DataStreams\src\query.jl:628
 [4] #stream!#122(::Bool, ::Array{Any,1}, ::Function, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::DataStreams.Data.Query{0x01,Tuple{DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},1,1,:pltid,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},2,2,:avgstdage,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},3,3,:avght,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},4,4,:diacnt,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},5,5,:sumd,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},6,6,:avgdia,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},7,7,:sumba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},8,8,:avgba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},9,9,:pmort,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},10,10,:alldiasum,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},11,11,:alldiacount,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},12,12,:allbasum,nothing,()}},(),nothing,nothing}, ::Type{DataFrames.DataFrame}) at e:\JuliaPkgDir\.julia\v0.6\DataStreams\src\query.jl:598
 [5] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::DataStreams.Data.Query{0x01,Tuple{DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},1,1,:pltid,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},2,2,:avgstdage,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},3,3,:avght,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},4,4,:diacnt,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},5,5,:sumd,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},6,6,:avgdia,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},7,7,:sumba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},8,8,:avgba,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},9,9,:pmort,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},10,10,:alldiasum,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Int64, Missings.Missing},11,11,:alldiacount,nothing,()},DataStreams.Data.QueryColumn{0x01,Union{Float64, Missings.Missing},12,12,:allbasum,nothing,()}},(),nothing,nothing}, ::Type{DataFrames.DataFrame}) at .\<missing>:0
 [6] #stream!#120(::Bool, ::Dict{Int64,Function}, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Void, ::Void, ::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::Type{DataFrames.DataFrame}) at e:\JuliaPkgDir\.julia\v0.6\DataStreams\src\query.jl:548
 [7] (::DataStreams.Data.#kw##stream!)(::Array{Any,1}, ::DataStreams.Data.#stream!, ::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Void}, ::Type{DataFrames.DataFrame}) at .\<missing>:0
 [8] #read#43(::Bool, ::Dict{Int64,Function}, ::Bool, ::Array{Any,1}, ::Function, ::String, ::Type{T} where T) at e:\JuliaPkgDir\.julia\v0.6\CSV\src\Source.jl:339
 [9] read(::String) at e:\JuliaPkgDir\.julia\v0.6\CSV\src\Source.jl:338_

**Comment by fab4ap** [comment]
I am using the Julia 0.6.3 with updated packages as of yesterday.

[ForResponsesCalc651.zip](https://github.com/JuliaData/CSV.jl/files/2085406/ForResponsesCalc651.zip)

**Comment by davidanthoff** [comment]
@fab4ap Until this gets fixed you can use [CSVFiles.jl](https://github.com/davidanthoff/CSVFiles.jl) which seems to read the file just fine.

**Comment by fab4ap** [comment]
Thanks very much!
Prasad

**Comment by crsl4** [comment]
Hello,
I am having a similar issue with a table that reads fine with readtable, but not with CSV.read.
I have a table with multiple spaces separating columns (not necessarily fixed size):
```
shell> head merlin.err
    FAMILY     PERSON     MARKER      RATIO
         A    EP01223   rs710865     0.0214
         A    EP01227 rs11249215     0.0107
         A    EP01228 rs11249215    0.00253
         A    EP01228 rs10903129     0.0116
```
The function `readtable` in `DataFrames` is able to read this table by treating repeated spaces as delimiter:
```
julia> using DataFrames
julia> dat=readtable("merlin.err",header=true, separator=' ')
WARNING: readtable is deprecated, use CSV.read from the CSV package instead
944×4 DataFrames.DataFrame
│ Row │ FAMILY     │ PERSON     │ MARKER     │ RATIO   │
├─────┼────────────┼────────────┼────────────┼─────────┤
│ 1   │ A          │ EP01223    │ rs710865   │ 0.0214  │
│ 2   │ A          │ EP01227    │ rs11249215 │ 0.0107  │
│ 3   │ A          │ EP01228    │ rs11249215 │ 0.00253 │
│ 4   │ A          │ EP01228    │ rs10903129 │ 0.0116  │
```
But I cannot do this with `CSV.read`, even with the `ignorerepeated` option:
```
julia> using CSV
julia> dat = CSV.read("merlin.err",header=true, delim=' ', ignorerepeated=true)
941×5 DataFrames.DataFrame
│ Row │ Column1    │ FAMILY     │ PERSON     │ MARKER     │ RATIO    │
│     │ String⍰    │ String⍰    │ String⍰    │ String⍰    │ Float64⍰ │
├─────┼────────────┼────────────┼────────────┼────────────┼──────────┤
│ 1   │ missing    │ A          │ EP01223    │ rs710865   │ 0.0214   │
│ 2   │ missing    │ A          │ EP01227    │ rs11249215 │ 0.0107   │
│ 3   │ missing    │ A          │ EP01228    │ rs11249215 │ 0.00253  │
│ 4   │ missing    │ A          │ EP01228    │ rs10903129 │ 0.0116   │
```

I am in julia 1.0.0, with CSV v0.4.3.
I attach a small text file to reproduce this example: [merlin-test.txt](https://github.com/JuliaData/CSV.jl/files/2737551/merlin-test.txt)
Any help is appreciated, thanks!!

**Comment by crsl4** [comment]
Sorry! I used the same issue because it would have the same title. I'll open a new one now.

**Comment by DrJonBall** [comment]
I am having a very similar issue, despite this being closed.  I am using CSV@0.6.1, Julia@1.4.0 and DataFrames@0.20.2.  The data are available here: https://data.sfgov.org/Economy-and-Community/Map-of-Registered-Businesses-San-Francisco/9tqe-vdng 

The data will not load using `CSV.read` but will load using `DataFrames.readtable`.  With `CSV.read` I get the following error:
```
ERROR: TaskFailedException:
ArgumentError: Day: 999 out of range (1:28)
Stacktrace:
 [1] Dates.Date(::Int64, ::Int64, ::Int64) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Dates\src\types.jl:223
 [2] typeparser at C:\JuliaPkgDir\.julia\packages\Parsers\HO51E\src\dates.jl:16 [inlined]
 [3] xparse at C:\JuliaPkgDir\.julia\packages\Parsers\HO51E\src\Parsers.jl:249 [inlined]
 [4] parsevalue!(::Type{Dates.Date}, ::Int8, ::Array{UInt64,1}, ::Array{UInt8,1}, ::Int64, ::Int64, ::Parsers.Options{false,false,true,false,Missing,UInt8,Nothing}, ::Int64, ::Int64, ::Array{Int8,1}, ::Array{Array{UInt64,1},1}) at C:\JuliaPkgDir\.julia\packages\CSV\76SRf\src\CSV.jl:1034
 [5] parsetape(::Val{false}, ::Bool, ::Int64, ::Dict{Int8,Int8}, ::Array{Array{UInt64,1},1}, ::Array{Array{UInt64,1},1}, ::Array{UInt8,1}, ::Int64, ::Int64, ::Int64, ::Nothing, ::Array{Int64,1}, ::Float64, ::Array{Dict{String,UInt64},1}, ::Array{UInt64,1}, ::Int64, ::Array{Int8,1}, ::Array{Int64,1}, ::Bool, ::Parsers.Options{false,false,true,false,Missing,UInt8,Nothing}, ::Bool) at C:\JuliaPkgDir\.julia\packages\CSV\76SRf\src\CSV.jl:744
 [6] macro expansion at C:\JuliaPkgDir\.julia\packages\CSV\76SRf\src\CSV.jl:584 [inlined]
 [7] (::CSV.var"#34#37"{Array{Int8,1},Array{UInt8,1},Parsers.Options{false,false,true,false,Missing,UInt8,Nothing},Float64,Int64,Bool,Dict{Int8,Int8},Int64,Nothing,Bool,Int64,Array{Int64,1},Int64,Array{Int64,1},Array{Array{Array{UInt64,1},1},1},Array{Array{Array{UInt64,1},1},1},Array{Array{Dict{String,UInt64},1},1},Array{Array{UInt64,1},1},Array{Array{Int8,1},1},Array{Array{Int64,1},1},Int64})() at .\threadingconstructs.jl:126
```

I suspect there is an incorrect date in there somewhere, but rather than simply fail, it may be better load the data and issue an alert - or handle it in whatever way DataFrames does.  This failure is a worry because DataFrames.readtable is deprecated.

**Comment by quinnj** [comment]
@DrJonBall, thanks for reporting this; that error indeed isn't following the normal error-flow model we have setup while parsing (it should replace with `missing` or promote the column to `String` depending on keywords passed). Curious if you're passing a `dateformat` keyword argument yourself? Or passing `types` somehow to force the column to be `Date`?

**Comment by quinnj** [comment]
@DrJonBall, I was able to reproduce the issue myself and found a fix: https://github.com/JuliaData/Parsers.jl/pull/51. Once that is merged and a new release tagged, this should fix the CSV.jl case (when you update Parsers). The correct behavior here should be that your column will be promoted to a String type if you're relying on CSV.jl to infer the column type; if you are passing the column type manually, then you should see a warning about the row/column where the invalid value was found, and the cell's value will be `missing`, and the column type will be promoted to `Union{Date, Missing}`. You can control this behavior a bit by passing `strict=true` which will throw an error when it encounters the invalid value, or `silencewarnings=true` which will suppress the warning printing while parsing.

**Comment by DrJonBall** [comment]
That sounds very promising.  In answer to your earlier question, no I was not passing in a dateformat keyword myself, just loading straight from the csv file.
